---
title: "Currentaccount"
output: html_document
date: "2023-10-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
df_filtered <-read.csv('BalanceOfPayment.csv',header = TRUE)
```

## Including Plots

You can also embed plots, for example:
```{r}
head(df_filtered)
```

```{r}
summary(df_filtered)
```
```{r}
currentaccount_df <- df_filtered[grepl("^Current Account", df_filtered$Indicator), ]

```
```{r}
write.csv(currentaccount_df, "current_account.csv")
```

```{r}
count <- nrow(currentaccount_df)
count
```

```{r}
unique_indi <- unique(currentaccount_df$Country)
unique_indi
```

```{r}
ggplot(currentaccount_df, aes(y = `X2015`, x = Indicator)) + 
  geom_boxplot(fill = "blue", color = "black", alpha = 1) + 
  labs(title = "Box Plot for currentaccount (2015)", x = "Indicator", y = "Value") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
library(ggplot2)
ggplot(currentaccount_df, aes(x = `X2015`, y = `X2020`)) + 
  geom_point(color = "blue", alpha = 0.7) + 
  labs(title = "Scatter Plot for current account (2015 vs 2020)", x = "2015", y = "2020")


```

```{r}

currentaccount_df

```
```{r}
currentaccount_df$Total <- rowSums(currentaccount_df[, grep("X20(15|16|17|18|19|20)", colnames(currentaccount_df))], na.rm = TRUE)
currentaccount_df
```
```{r}
credit_data <- currentaccount_df[currentaccount_df$Indicator == "Current Account, Goods and Services, Credit, US Dollars", ]

# Filter rows where Indicator contains "Debit"
debit_data <- currentaccount_df[currentaccount_df$Indicator == "Current Account, Goods and Services, Debit, US Dollars", ]

credit_grouped <- aggregate(Total ~ Country, data = credit_data, sum)
debit_grouped <- aggregate(Total ~ Country, data = debit_data, sum)

trade_balance_data_total <- merge(credit_grouped, debit_grouped, by = "Country", all = TRUE)
trade_balance_data_total$Trade_Balance <- trade_balance_data_total$Total.x - trade_balance_data_total$Total.y
trade_balance_data_total$Trade_Balance_mean <- trade_balance_data_total$Trade_Balance /6
print(trade_balance_data_total)
```
```{r}
credit_data_income <- currentaccount_df[currentaccount_df$Indicator == "Current Account, Primary Income, Investment Income, Direct Investment, Credit, US Dollars", ]

# Filter rows where Indicator contains "Debit"
debit_data_income <- currentaccount_df[currentaccount_df$Indicator == "Current Account, Primary Income, Investment Income, Direct Investment, Debit, US Dollars", ]

credit_grouped_income <- aggregate(Total ~ Country, data = credit_data_income, sum)
debit_grouped_income <- aggregate(Total ~ Country, data = debit_data_income, sum)

income_balance_data_Total <- merge(credit_grouped_income, debit_grouped_income, by = "Country", all = TRUE)
income_balance_data_Total$income_Balance <- income_balance_data_Total$Total.x - income_balance_data_Total$Total.y
income_balance_data_Total$income_Balance_mean <- income_balance_data_Total$income_Balance /6
print(income_balance_data_Total)
```
```{r}
credit_data_transport <- currentaccount_df[currentaccount_df$Indicator == "Current Account, Goods and Services, Services, Transport, Credit, US Dollars", ]

# Filter rows where Indicator contains "Debit"
debit_data_transport <- currentaccount_df[currentaccount_df$Indicator == "Current Account, Goods and Services, Services, Transport, Debit, US Dollars", ]

credit_grouped_transport <- aggregate(Total ~ Country, data = credit_data_transport, sum)
debit_grouped_transport <- aggregate(Total ~ Country, data = debit_data_transport, sum)

transport_balance_data_Total <- merge(credit_grouped_transport, debit_grouped_transport, by = "Country", all = TRUE)
transport_balance_data_Total$transport_Balance <- transport_balance_data_Total$Total.x - transport_balance_data_Total$Total.y
transport_balance_data_Total$transport_Balance_mean<-transport_balance_data_Total$transport_Balance/6
print(transport_balance_data_Total)
```
```{r}
merged_df <- merge(trade_balance_data_total, income_balance_data_Total, by = "Country")
merged_df <- merge(merged_df, transport_balance_data_Total, by = "Country")
result_df <- merged_df[, c("Country", "Trade_Balance", "Trade_Balance_mean", "income_Balance", "income_Balance_mean", "transport_Balance", "transport_Balance_mean")]
result_df
```
```{r}
 write.csv(result_df, "account_balance.csv", row.names = FALSE)
```

```{r}
library(dplyr)


# Sort the original data frame by the "Total" column in descending order (highest to lowest)
df_sorted_descending <- result_df %>% arrange(desc(Trade_Balance_mean))

# Select the top 10 "Total" values
top_20 <- head(df_sorted_descending, 20)
top_20



# Combine the top 10 and bottom 10 into a single data frame
combined_df_total <- bind_rows(top_20)

combined_df_total

```

```{r}
ggplot(combined_df_total, aes(x = `Trade_Balance_mean`, y = `transport_Balance_mean`, color = Country)) + 
  geom_point() + 
  labs(title = "Scatter Plot for trade and transport balance of total mean ", x = "Trade_Balance_mean", y = "transport_Balance_mean")

```
```{r}
t_test_result_current <- t.test(combined_df_total$Trade_Balance_mean, combined_df_total$transport_Balance_mean, paired = TRUE)
t_test_result_current
```
```{r}
t_test_result_current_171 <- t.test(result_df$Trade_Balance_mean, result_df$transport_Balance_mean, paired = TRUE)
t_test_result_current_171

```
```{r}
result_df$Current_Account_Balance <- result_df$Trade_Balance + result_df$income_Balance + result_df$transport_Balance
result_df
```
```{r}
ggplot(result_df, aes(x = Current_Account_Balance)) +
  geom_density() +
  labs(title = "Density Plot of Current Account Balance")
```
```{r}
ggplot(result_df, aes(x = Current_Account_Balance)) +
  geom_histogram(fill = "lightblue", color = "black") +
  labs(title = "Histogram of Current Account Balance", x = "Current Account Balance")
```