---
title: "Project Team ASAB"
output: html_document
date: "2023-09-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df <- read.csv('BOP_09-13-2023 17-28-15-94_timeSeries.csv',header = TRUE)

c <-nrow(df)
print(c)
```
## Selecting the Indicators which are require for solving our SMART question.

```{r}
unique_names <- unique(df$Indicator.Name)

```
```{r}
value_count <- table(df$Indicator.Name)
filtered_values <- names(value_count[value_count > 192])
filtered_values
```

```{r}
colnames(df)[1] <- 'Country'
colnames(df)[2] <- 'Code'
colnames(df)[3] <- 'Indicator'
colnames(df)[4] <- 'Icode'
colnames(df)[6] <- '2015'
colnames(df)[7] <- '2016'
colnames(df)[8] <- '2017'
colnames(df)[9] <- '2018'
colnames(df)[10] <- '2019'
colnames(df)[11] <- '2020'
str(df)
```
## Removing the unnecessary columns.

```{r}
df$Attribute <- NULL

```

## New data frame.
```{r}
str(df)
```

## Removing the unneccassary rows from the df using indicator column.
```{r}
df <- subset(df, Indicator %in% c('Capital Account, Capital Transfers, Credit, US Dollars','Capital Account, Capital Transfers, Net, US Dollars','Capital Account, Total, Credit, US Dollars','Capital Account, Total, Debit, US Dollars','Capital Account, Total, Net, US Dollars','Current Account, Goods and Services, Credit, US Dollars','Current Account, Goods and Services, Debit, US Dollars','Current Account, Goods and Services, Services, Transport, Credit, US Dollars','Current Account, Goods and Services, Services, Transport, Debit, US Dollars','Current Account, Primary Income, Investment Income, Direct Investment, Credit, US Dollars','Current Account, Primary Income, Investment Income, Direct Investment, Debit, US Dollars','Supplementary Items, Reserve Assets (with Fund Record), US Dollars','Supplementary Items, Reserve Position in the Fund (with Fund Record), US Dollars','Financial Account, Net Lending (+) / Net Borrowing (-) (Balance from Financial Account), Direct Investment, Net Acquisition of Financial Assets, Equity and Investment Fund Shares, Equity Other Than Reinvestment of Earnings, US Dollars','Financial Account, Net Lending (+) / Net Borrowing (-) (Balance from Financial Account), Direct Investment, Net Acquisition of Financial Assets, Equity and Investment Fund Shares, US Dollars','Financial Account, Net Lending (+) / Net Borrowing (-) (Balance from Financial Account), Direct Investment, Net Acquisition of Financial Assets, US Dollars','Financial Account, Net Lending (+) / Net Borrowing (-) (Balance from Financial Account), Direct Investment, Net Incurrence of Liabilities, Debt Instruments, US Dollars','Financial Account, Other Investment, Loans, Net Acquisition of Financial Assets, US Dollars','Financial Account, Other Investment, Loans, Net Incurrence of Liabilities, General Government, Other Long-term, US Dollars','Financial Account, Other Investment, Loans, Net Incurrence of Liabilities, General Government, US Dollars','Financial Account, Other Investment, Loans, Net Incurrence of Liabilities, Other Sectors, Long-term, US Dollars','Financial Account, Other Investment, Loans, Net Incurrence of Liabilities, Other Sectors, US Dollars','Financial Account, Other Investment, Loans, Net Incurrence of Liabilities, US Dollars','Financial Account, Other Investment, Loans, US Dollars','Financial Account, Portfolio Investment, Net Acquisition of Financial Assets, Debt Securities, US Dollars','Financial Account, Portfolio Investment, Net Acquisition of Financial Assets, Equity and Investment Fund Shares, US Dollars','Financial Account, Portfolio Investment, Net Acquisition of Financial Assets, US Dollars','Financial Account, Portfolio Investment, Net Incurrence of Liabilities, Debt Securities, US Dollars','Net Lending (+) / Net Borrowing (-) (Balance from Current and Capital Account), US Dollars','Supplementary Items, Total Current + Capital Account, US Dollars','Supplementary Items, Portfolio Investment, Net Incurrence of Liabilities (Excluding Exceptional Financing), US Dollars'))
```


```{r}
df$X2021 <- NULL
df$X2022 <- NULL
df$X2023 <- NULL
df$X <- NULL
```


## Now saving this updated csv file in local system.
```{r}
write.csv(df, "BOPS.csv")
```


```{r}
summary(df)
```

```{r}

df_50 <- subset(df, Country %in% c('Lebanon','Lesotho, Kingdom of','Liberia','Libya','Lithuania','Luxembourg','Madagascar, Rep. of','Malawi','Malaysia','Maldives','Mali','Malta','Marshall Islands, Rep. of the','Mauritania, Islamic Rep. of','Mauritius','Mexico','Moldova, Rep. of','Mongolia','Montenegro','Montserrat', 'Morocco','Mozambique, Rep. of','Myanmar','Namibia','Nauru, Rep. of','Nepal','Netherlands, The','New Caledonia','New Zealand','Nicaragua','Niger','Nigeria','North Macedonia, Republic of','Norway','Oman','Pakistan','Palau, Rep. of','Panama','Papua New Guinea','Paraguay','Peru','Philippines','Poland, Rep. of','Portugal','Qatar','Romania','Russian Federation','Rwanda','Samoa','São Tomé and Príncipe, Dem. Rep. of'))


```


```{r}
summary(df_50)

```

```{r}
str(df_50)
```
```{r}
# Convert specific columns to numeric in df_50
df_50[["2015"]] <- as.numeric(df_50[["2015"]])
df_50[["2016"]] <- as.numeric(df_50[["2016"]])
df_50[["2017"]] <- as.numeric(df_50[["2017"]])
df_50[["2018"]] <- as.numeric(df_50[["2018"]])
df_50[["2019"]] <- as.numeric(df_50[["2019"]])
df_50[["2020"]] <- as.numeric(df_50[["2020"]])



```


```{r}
write.csv(df_50, "BOPS1.csv")
```

```{r}
# Assuming 'bop_data' is your dataset
# Replace '2015', '2016', ..., '2020' with the actual column names for those years

# Create a logical vector indicating rows where ALL values from 2015 to 2020 are NULL or non-numeric
row_indices_to_delete <- apply(df_50[, c('2015', '2016', '2017', '2018', '2019', '2020')], 1, function(row) {
  all(is.na(row) )
})

# Subset your dataset to keep only rows where all values from 2015 to 2020 are NOT NULL and numeric
cleaned_bop_data <- df_50[!row_indices_to_delete, ]

# Now 'cleaned_bop_data' contains the rows where not all values from 2015 to 2020 are NULL or non-numeric
df_50_cleaned <- df_50[!row_indices_to_delete, ]


```

```{r}
write.csv(df_50_cleaned, "BOPS2.csv")
```

```{r}
c3 <- nrow(df)
c1 <- nrow(df_50)
c2 <- nrow(df_50_cleaned)
c3
c1
c2
```

```{r}
# Assuming 'bop_data' is your dataset
# Replace '2015', '2016', ..., '2020' with the actual column names for those years

# Count the number of NA or 0 values in each row for the 2015 to 2020 columns
count_na <- rowSums(is.na(df_50_cleaned[, c('2015', '2016', '2017', '2018', '2019', '2020')]))

# Define a threshold (5 out of 6) for deletion
threshold <- 1

# Subset your dataset to keep only rows where the count is less than the threshold
df_50_cleaned <- df_50_cleaned[count_na < threshold, ]

# Now 'cleaned_bop_data' contains the rows where 5 out of 6 values from 2015 to 2020 are not NA and not equal to 0


```

```{r}
summary(df_50_cleaned)
unique_names_1 <- unique(df_50_cleaned$Indicator)
unique_names_1
```
```{r}
# Assuming 'bop_data' is your dataset and 'Country' is the column with country names

# Use the 'table()' function to count the occurrences of each country
country_counts <- table(df_50_cleaned$Country)

# Convert the result to a data frame for better visualization (optional)
country_counts_df <- as.data.frame(country_counts)

# Rename the columns for clarity (optional)
colnames(country_counts_df) <- c("Country", "Count")

# Print or view the counts
print(country_counts_df)

```
```{r}

# Assuming 'bop_data' is your dataset and 'Country' is the column with country names

# Calculate the count of occurrences for each country
country_counts <- table(df_50_cleaned$Country)

# Find the countries where the count is at least 20
countries_to_keep <- names(country_counts[country_counts >= 20])

# Filter the dataset to keep only the rows with countries that meet the criteria
filtered_bop_data <- df_50_cleaned[df_50_cleaned$Country %in% countries_to_keep, ]

# Now 'filtered_bop_data' contains the data for countries with at least 20 occurrences


```

```{r}
write.csv(filtered_bop_data, "BOPS_filtered.csv")
```

```{r}
country_counts <- table(filtered_bop_data$Country)

# Convert the result to a data frame for better visualization (optional)
country_counts_df <- as.data.frame(country_counts)

# Rename the columns for clarity (optional)
colnames(country_counts_df) <- c("Country", "Count")

# Print or view the counts
country_counts_df

```

```{r}
c4 <- nrow(filtered_bop_data)
c4
```